import * as esbuild from 'esbuild';
import { readFileSync, writeFileSync } from 'node:fs';

const watch = process.argv.includes('--watch');
const pkg = JSON.parse(readFileSync(new URL('./package.json', import.meta.url), 'utf8'));

// The omp bundle (defines <ia-player> and <omp-images>). rdflib stays
// external — the host page's component-interop importmap maps it to the one
// shared instance. CSS/HTML are inlined as text by bundle-init.js.
const options = {
  entryPoints: ['src/ia-player/bundle-entry.js'],
  outfile: 'dist/ia-player.esm.js',
  format: 'esm',
  bundle: true,
  minify: true,
  target: ['es2020'],
  platform: 'browser',
  mainFields: ['module', 'browser', 'main'],
  conditions: ['module', 'import', 'browser', 'default'],
  treeShaking: true,
  legalComments: 'none',
  logLevel: 'info',
  external: ['rdflib'],
  loader: { '.css': 'text', '.html': 'text' },
  define: {
    __OMP_BUILD__: JSON.stringify(`omp ${pkg.version} ${new Date().toISOString()}`),
    __OMP_VERSION__: JSON.stringify(pkg.version),
  },
};

// dist/omp-images.esm.js — a shim so the <omp-images> plugin entry can name
// a module whose FILENAME matches its tag (the filename==tag convention of
// ui:Plugin entries; the tag derives from the module basename). Importing it
// side-effect-registers both tags via the shared bundle.
const SHIM =
  '// generated by esbuild.config.mjs — <omp-images> is defined by the shared\n' +
  '// ia-player bundle; this shim exists so the plugin entry can point at a\n' +
  '// module named after its tag.\n' +
  "import './ia-player.esm.js';\n";

if (watch) {
  const ctx = await esbuild.context(options);
  await ctx.watch();
  console.log('esbuild: watching src/');
} else {
  await esbuild.build(options);
  writeFileSync(new URL('./dist/omp-images.esm.js', import.meta.url), SHIM);
  console.log('wrote dist/omp-images.esm.js (tag-name shim → ia-player.esm.js)');
}
